name: Deploy Static Site via AWS CDK
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Node.js Runtime
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      #install and build astro frontend application.
      - name: Install frontend dependencies
        run: npm ci

      - name: Build astro static site
        run: npm run build


      #install cdk infrastructure stack
      - name: Install Project & CDK Dependencies
        working-directory: ./hello-cdk  
        run: npm ci
      

      #authenticate with aws
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

     - name: Deploy Infrastructure & Assets with AWS CDK
       working-directory: ./hello-cdk
       run: npx cdk deploy --require-approval never
